### ISSUE TITLE
AdminClient creation: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position

### ISSUE THREAD

**Issue by tnielens-centrica** [zio/zio-kafka#1115]
I upgraded zio-kafka from 2.1.1 to 2.7.0 and bump into jvm bytecode compatibility issues.

My code 
```
  val kafkaLayer: ULayer[KafkaContainer] = ZLayer.succeed {
    val container = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:6.2.1"))
      .withReuse(true)
    container.start()
    container
  }
  val adminClientLayer: ZLayer[KafkaContainer, Throwable, AdminClient] = ZLayer.scoped(for {
    kafkaContainer <- ZIO.service[KafkaContainer]
    client <- AdminClient
      .make(AdminClientSettings(List(kafkaContainer.getBootstrapServers)))
      .debug("debug admin client creation")
  } yield client)
  ```
  
  The error printed in the console from the `debug()` call above: 
```
<FAIL> debug admin client creation: Fail(org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient,Stack trace for thread "zio-fiber-26":
    at zio.kafka.utils.SslHelper.doValidateEndpoint(SslHelper.scala:89)
    at zio.kafka.utils.SslHelper.doValidateEndpoint(SslHelper.scala:75)
    at zio.kafka.utils.SslHelper.doValidateEndpoint(SslHelper.scala:74)
    at zio.kafka.utils.SslHelper.doValidateEndpoint(SslHelper.scala:100)
    at zio.kafka.utils.SslHelper.doValidateEndpoint(SslHelper.scala:101)
    at zio.kafka.admin.AdminClient.javaClientFromSettings(AdminClient.scala:1518)
    at zio.kafka.admin.AdminClient.javaClientFromSettings(AdminClient.scala:1519)
    at zio.kafka.admin.AdminClient.fromScopedJavaClient(AdminClient.scala:1509)
        at ... <my frames here>
 ```
        
This issue isn't helpful and hides a nested cause that isn't printed. From inspection with the debugger, this is the cause of the exception above
 ```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at zio.kafka.utils.SslHelper$.unsafeReadAnswerFromTestRequest(SslHelper.scala:236)
	at zio.kafka.utils.SslHelper$.$anonfun$validateSslConfigOf$2(SslHelper.scala:193)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at zio.ZIOCompanionPlatformSpecific.$anonfun$attemptBlockingInterrupt$6(ZIOPlatformSpecific.scala:105)
	at zio.ZIO$.$anonfun$suspend$1(ZIO.scala:4624)
	at zio.FiberRef$unsafe$$anon$2.$anonfun$getWith$1(FiberRef.scala:474)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1067)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

This issue seems to be well described here: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

This ticket highlights two problems
- ~the error handling doesn't report the root cause (unless I don't understand some of zio's error handling specificities, which might very well be the case :))~
- there is a bytecode compatibility issue that can be solved with a javac compilation option. The solution is described in the blogpost. I'm not sure it's usable from scalac though.

Edit: nvm on the remark about lost error information. I have some issues with how zio-test prints errors. zio-kafka properly chains exception causes.

**Comment by tnielens** [comment]
I didn't notice the mention in the 2.5.0 release note about jdk8 support drop. It's not clear from the release note why. Any dependency issue? or jdk11 features zio-kafka wanted to leverage?

**Comment by erikvanoosten** [comment]
> I didn't notice the mention in the 2.5.0 release note about jdk8 support drop. It's not clear from the release note why. Any dependency issue? or jdk11 features zio-kafka wanted to leverage?

Most probably we just went along with zio-sbt.

@guizmaii do you know more about this?

**Comment by tnielens** [comment]
If you need jdk11 for zio-sbt (build tooling), I suspect you can still publish jdk8 compatible artifacts with the `-release 8` scalac option. I tested the modification in the PR with my project and that solved the `NoSuchMethodError` issue.

**Comment by guizmaii** [comment]
Dropping Java8 support is a global ZIO decision. All the ZIO libs will progressively drop it. We can only encourage you to update to Java 17. It'll bring a lot of performance improvements to you.

**Comment by tnielens** [comment]
Could the class format 55 be used then? @guizmaii 
https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-4.html
The error would be a clearer as today's class files seem still jdk8 compatible. The failure above is due to a std library api change.

**Comment by guizmaii** [comment]
AFAIR, we're using JDK11 class files
See:
- https://github.com/zio/zio-sbt/blob/main/zio-sbt-ecosystem/src/main/scala/zio/sbt/ScalaCompilerSettings.scala#L94
- https://github.com/zio/zio-sbt/blob/main/zio-sbt-ecosystem/src/main/scala/zio/sbt/ScalaCompilerSettings.scala#L161
