### ISSUE TITLE
Handle java.lang.IllegalStateException: No current assignment for partition 

### ISSUE THREAD

**Issue by marcins83** [zio/zio-kafka#126]
Sometimes, I am getting IllegalStateException and consumer stop feeding from Kafka. 
Stacktrace:
```
Fiber failed.
A checked error was not handled.
java.lang.IllegalStateException: No current assignment for partition test-topic-13
	at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:356)
	at org.apache.kafka.clients.consumer.internals.SubscriptionState.resume(SubscriptionState.java:662)
	at org.apache.kafka.clients.consumer.KafkaConsumer.resume(KafkaConsumer.java:2012)
	at zio.kafka.client.internal.Runloop$.$anonfun$apply$29(Runloop.scala:331)
	at zio.Task$.$anonfun$effectSuspend$1(Task.scala:195)
	at zio.internal.FiberContext.liftedTree1$1(FiberContext.scala:546)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:546)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:661)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Fiber:Id(1582406036469,10490784) was supposed to continue to:
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:147)
  a future continuation at zio.kafka.client.internal.ConsumerAccess$$anonfun$withConsumerNoPermit$2.apply(ConsumerAccess.scala:23)

Fiber:Id(1582406036469,10490784) execution trace:
  at zio.Task$.effectSuspend(Task.scala:195)
  at zio.ZIOFunctions.effectSuspend(ZIO.scala:2003)
  at zio.ZIO.bracket_(ZIO.scala:147)
  at zio.internal.FiberContext.lock(FiberContext.scala:606)
  at zio.internal.FiberContext.lock(FiberContext.scala:606)
  at zio.blocking.Blocking$Service.blocking(Blocking.scala:69)
  at zio.blocking.package$.blockingExecutor(blocking.scala:23)

Fiber:Id(1582406036469,10490784) was spawned by:

Fiber:Id(1582405673386,9919483) was supposed to continue to:
  a future continuation at zio.kafka.client.internal.ConsumerAccess.withConsumerNoPermit(ConsumerAccess.scala:26)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.Semaphore.withPermits(Semaphore.scala:101)
  a future continuation at zio.kafka.client.internal.Runloop$.apply(Runloop.scala:232)
  a future continuation at zio.kafka.client.internal.Runloop$.apply(Runloop.scala:232)
  a future continuation at zio.stream.ZStream.foldWhileManagedM(ZStream.scala:1460)
  a future continuation at zio.stream.ZStream.foldM(ZStream.scala:1384)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)
  a future continuation at zio.ZManaged.use(ZManaged.scala:748)
  a future continuation at zio.ZIO.run(ZIO.scala:1166)

Fiber:Id(1582405673386,9919483) execution trace:
  at zio.Semaphore.withPermits(Semaphore.scala:102)
  at zio.Semaphore.withPermits(Semaphore.scala:102)
  at zio.Ref$.modify$extension(Ref.scala:53)
  at zio.Semaphore.prepare(Semaphore.scala:131)
  at zio.Promise$.makeAs(Promise.scala:248)
  at zio.Promise$.make(Promise.scala:241)
  at zio.ZIOFunctions.fiberId(ZIO.scala:2054)
  at zio.ZIOFunctions.descriptor(ZIO.scala:1874)
  at zio.kafka.client.internal.Runloop$.apply(Runloop.scala:441)
  at zio.Ref$.get$extension(Ref.scala:41)
```

Code:
```
Consumer.make(consumerSettings)
  .use { consumer =>
    consumer
      .subscribeAnd(Subscription.topics(config.kafka.topic))
      .plainStream(Serde.string, Serde.string)
      .flattenChunks
      .mapM(decoding)
      .mapMPar(config.parallelism) {
        case (offset, Some(event)) =>
          processing(offset, event)
        case (offset, _) =>
          ZIO.succeed(offset)
       }
       .aggregateAsyncWithin(Consumer.offsetBatches, scheduler)
       .mapM(_.commit)
       .runDrain
       .forever
  }
```

**Comment by svroonland** [comment]
@marcins83 Are you running this with a consumer group of 1 or are there multiple consumers? I have a possible explanation of the bug but it would only occur under consumer group rebalancing.

**Comment by marcins83** [comment]
@svroonland I have multiple consumers in one group. It is happening exactly consumer group rebalancing.

**Comment by svroonland** [comment]
Alright. I have a suspicion what's causing it, will work on a fix.

**Comment by svroonland** [comment]
I've been staring at it for a good while, but so far haven't discovered a code path that can trigger this error yet.

**Comment by svroonland** [comment]
Any idea what caused this condition to appear @iravid ?  I couldn't figure it out

**Comment by iravid** [comment]
I saw it happen in production too, but unfortunately could not reproduce. I think this happens when rebalances are spread out across several polls and requests come in for revoked partitions. Not sure though how requests could get inserted into the state when the partitions are not currently assigned 🤷🏽‍♂️

I think this will do for now.
