### ISSUE TITLE
OOM Exception in version 2.3.1

### ISSUE THREAD

**Issue by jgordijn** [zio/zio-kafka#918]
I am getting OOM exceptions while processing a kafka topic with 4mln backlog. Whenever I start the app with version `2.3.1`, I get the exception below. It works fine when I revert back to version `2.0.7`

The code:
```scala
def run(): UIO[Unit] =
    ZIO
      .scoped {
        ZIO.logInfo(s"Starting consumer on: ${topic.value}") *>
        Consumer.make(KafkaEventStreamImpl.consumerSettings(configuration)).flatMap { consumer =>
          consumer
            .plainStream(Subscription.topics(topic.value), Serde.string, Serde.string)
            .map { cr => cr.offset }
            .mapZIO(batch => batch.commitOrRetry(Schedule.exponential(1.second) && Schedule.recurs(3)))
            .runDrain
            .tapError(e => ZIO.logErrorCause(s"Error", Cause.fail(e)))
        }
      }
      .sandbox
      .tapError(e => ZIO.logErrorCause(s"Error", Cause.fail(e)))
      .ignore
```

```
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.nio.HeapByteBuffer.<init>(Unknown Source)
        at java.base/java.nio.ByteBuffer.allocate(Unknown Source)
        at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:102)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:321)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsAsync(ConsumerCoordinator.java:1120)
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitAsync(KafkaConsumer.java:1574)
        at zio.kafka.consumer.internal.Runloop.$anonfun$doCommit$11(Runloop.scala:133)
        at zio.kafka.consumer.internal.Runloop$$Lambda$3870/0x000000080166dc28.apply$mcV$sp(Unknown Source)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at zio.ZIOCompanionVersionSpecific.$anonfun$attempt$1(ZIOCompanionVersionSpecific.scala:100)
        at zio.ZIOCompanionVersionSpecific$$Lambda$388/0x0000000800e141e0.apply(Unknown Source)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:904)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1174)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:948)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
```

**Comment by jgordijn** [comment]
I did some further testing. 
Version 2.2 also still works.
2.3.0 starts with OOM exceptions.

**Comment by guizmaii** [comment]
Some users already reported this issue with `2.3.x`, see https://discord.com/channels/629491597070827530/629497941719121960/1105886943180505188.

@erikvanoosten Do you have any more advice to give to resolve this OOM, maybe?

**Comment by erikvanoosten** [comment]
> @erikvanoosten Do you have any more advice to give to resolve this OOM, maybe?

1. Disable optimistic resume with version 2.3.2.
2. Use .bufferChunks(1) or .bufferChunks(2) on the stream to restore buffering.

Step 2 restores the prefetching feature that was removed in 2.3. If you still keep getting OOM, use less pre-fetching.

**Comment by erikvanoosten** [comment]
Another tip: analyze the consumer settings. Some consumer settings require more memory. If you don't know, try reverting to the default values.

@jgordijn, please keep us up to date on what worked for you. This will help us direct our focus.

**Comment by jgordijn** [comment]
Disabling `optimistic resume` seems to solve the OOM.

**Comment by guizmaii** [comment]
@erikvanoosten I think that regarding all these pieces of information coming from our users, it'd be good to reconsider the viability of this "optimistic resume" optimisation.
It seems to improve things in the very limited and narrowed scope of our micro-benchmarks but on real-world workloads, we see that it creates important latency issues and apparently important memory consumption issues too.

I'd like to suggest removing it. WDYT?

Cc @svroonland

**Comment by erikvanoosten** [comment]
Given the evidence, I am not against removing it.

I do still think we need some pre-fetching, the low latency use cases do not go away and they need this optimization very much.

We do need to think about a replacement:
1. we can bring back pre-fetching (also causes heavy OOM in some use cases)
2. we can instruct people to do buffering themselves using `bufferChunks` (does not work for all consumer methods)
3. we improve optimistic pre-fetching by replacing the fairly naïve pattern matching implementation with something smarter
4. we revive @svroonland 's PR for pre-fetching but with smarter automatic dimensioning
5. or we simply keep it, but disable it by default (this would be a quick win)

**Comment by myazinn** [comment]
> How did you fix your OOM issue you reported here:

I didn't 😄 Just decided to use previous version until I could find a way to reproduce it in a smaller example (but I couldn't do it anyway).

**Comment by guizmaii** [comment]
@jgordijn In [v2.4.0](https://github.com/zio/zio-kafka/releases/tag/v2.4.0), we removed the "optimistic resume" we introduced in [v.2.3.0](https://github.com/zio/zio-kafka/releases/tag/v2.3.0)

I close the issue. Feel free to ask us to reopen it if you think we didn't address your issue.
Thanks for your report and help 🙂
